### ISSUE TITLE
Angular 6 plans?

### ISSUE THREAD

**Issue by mohamedaarab1994** [biig-io/ngx-smart-modal#110]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ X ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
Ngx-smart-modal is on Angular 5 at the moment and may be incompatible with Angular 6 apps.

**Expected behavior**
Update the library to support Angular 6

**Reproduction of the problem**
I don't have any problems at this moment.

**What is the motivation / use case for changing the behavior?**
With the new update of Angular, they have introduced new RxJS features and some minor features that boosts the performance of your app.

**Please tell us about your environment:**
* **Angular version:** 5.1.x

* **Browser:** All

* **Language:** TypeScript 2.7

**Comment by maximelafarie** [comment]
Hi @mohamedaarab1994!

Excellent question!

Indeed, we gonna update the library with a new version dedicated to Angular 6. We have a project to refactor the tags of the library since it became more popular. 😉 

Stay tuned! 🖖

**Comment by jkon** [comment]
this would be nice, because i am already on angular 6 with an app and while this component is super useful, I'm having issues with z-indexes and I'm not sure if it is an incompatibility with angular 6 or just my codebase. It seems that it works fine some places, but depending on where in the dom the component is, it doesn't put the modal on top of everything. 
Before this component, I was using ng2-bs3-modal (before I started using angular material styling for everything). It would attach the modal component to the body, which made managing z-index a little easier. Could you explain why you don't attach to the body, or give any suggestions on managing z-index issues.

**Comment by khylias** [comment]
Hi @jkon,

thanks for your interest in our component, it makes us really happy!

For your z-index problem, I don't think it's related to Angular 6, but rather the CSS style in your application. To best manage the z-indexes, you can put all your modals in the `app.component.html` if you wish, and then manage them with the `NgxSmartModalService`. This will allow you to have modals at body level, or at least very close, and a simplified management.

**Comment by maximelafarie** [comment]
Hi @jkon,

We also use this library on Angular 6 projects without any problem. 😉If we do something on the library relative to Angular 6, it will be the upgrade of library imports and latests RxJS methods.

For your question about the modal relative to the `body`, you can check the following issue : #102 

Happy coding 🖖

**Comment by jkon** [comment]
@khylias, thanks for the idea to move them up towards the app.component level. I moved the ones that were giving me trouble to a container one level down from the main app component and now they work great. I wish I understood a little better why the z-index works that way and not more absolutely, but I get now that it has something to do with the position and that helps a lot.

**Comment by maximelafarie** [comment]
Since the release of Angular 6 and 7, the team is thinking about a way of using last versions of RxJS and new Angular API to boost the library up. Given that there's nothing official and decided at this time, I can't tell if we're going to use RxJS as dependency again or not. 
But from now, each next release will follow the Angular release version with adapted dependencies. 

I'm closing this issue according to what I said above.

🖖
