### ISSUE TITLE
Modal cannot be opened on ngOnInit/ngAfterViewInit

### ISSUE THREAD

**Issue by chris1302** [biig-io/ngx-smart-modal#114]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

Currently the modal is not shown when trying to open it on ngOnInit/ngAfterViewInit of app.component because it is not registered yet. It is only working with a setTimeout().

**Expected behavior**

I would expect that the modal can be opened without a setTimeout().

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

I would like to show a modal automatically after the login without user interaction.

**Please tell us about your environment:**

* **Smart Modal version:** 2.0.3

* **Angular version:** 5.2.x

* **Browser:** [all]

* **Language:** [all]

**Comment by maximelafarie** [comment]
Hi @chris1302!

Since the library isn't fully loaded at `AppComponent` init time, opening a modal with the library's API is impossible at this time.

I guess we can do something [like we've done on NgxSmartLoader](https://github.com/biig-io/ngx-smart-loader/issues/2) (which is using the same API strategy than NgxSmartModal). We could reproduce it.
