### ISSUE TITLE
Fade-out animation request

### ISSUE THREAD

**Issue by Kalpesh300** [biig-io/ngx-smart-modal#130]
**I'm submitting a ...**  
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

Currently, you provide some custom classes to open modal with some animation. But when we close modal with some outer click or ESC key, it doesn't reverse the effect by which it was opened.
For example, if modal is opened from left to right, at the time of closing it should be animated from left to right movement.

**What is the motivation / use case for changing the behavior?**
It provides better user experience with consistency of opening and closing modal.

**Comment by maximelafarie** [comment]
Hi @Kalpesh300!

Maybe I don't understand your issue, but it seems to work perfectly on the demo ("Data in modal" button).

Anyway, can you tell me the version of NgxSmartModal you're using please ?

**Comment by Kalpesh300** [comment]
It is working completely fine. There was a mistake made by me only. Thanks for quick response. I want to add one more suggestion that please don't wrap modal-dialog into the overlay in HTML. If this two thing can be separated it would be more easy to add custom animations to overlay without touching modal-dialog. Further, you can add more effects like blur and other filters for the overlay.

Thanks for the response.

**Comment by maximelafarie** [comment]
Happy to see your issue solved! 😉 

Separating overlay and modal markup is a big deal. In previous versions the modal markup was a sibling of the overlay markup. Then, for modal position calculation and other things, it has been wrapped into it.

Styling with the current markup is a little trickier than previous versions because modal animations relies on the overlay (if it's hidden or not).

That's why there is a delay between modal animations and overlay animations to avoid style glitches and other weird behaviours.

We'll thought about a better approach on how to make animations easier. 😎 

Happy coding! 🖖
