### ISSUE TITLE
Prevent redundant keyup-listeners from being registered

### ISSUE THREAD

**Issue by Ian-Emsens** [biig-io/ngx-smart-modal#133]
**I'm submitting a feature request**
```
[ ] bug report
[ x ] feature request
[ ] support request
```

**Current behavior**
Currently, instantiating any ngx-smart-modal register a keyup listener on the document, this causes exponential performance issues when a modal appears in a looped component.

Yes, I am aware the solution for this is to treat a modal like a singleton and ensure it is only declared once but that is not the point here.

**Expected behavior**
A listener should only be created when the corresponding config parameter requires it to be so.
e.g. a ngx-smart-modal where `escapable` is false should not register a `keyup` listener on the document.

**Reproduction of the problem**

- Two modals appear in my list of 139 items, 7 appear outside of the list:
![image](https://user-images.githubusercontent.com/5319267/44267854-08871300-a230-11e8-8a98-f97509d47d21.png)

- After removing both modals:
![image](https://user-images.githubusercontent.com/5319267/44267865-163c9880-a230-11e8-8c9e-74fa304ab7c9.png)

**What is the motivation / use case for changing the behavior?**
Behavior that is configured to be disabled should be completely disabled.

**Please tell us about your environment:**
macOS High Sierra 10.13.6

* **Smart Modal version: 6.0.4**

* **Angular version: 5.2.11**

* **Browser: all**

* **Language: Typescript**

**Comment by maximelafarie** [comment]
Hi @Ian-Emsens, thank you for submitting us your issue.

Indeed, that's a big performance issue and it shall be fixed in next release.
Treating modals as singleton is a interesting thing but is not mandatory for the moment. As you said, we need to enhance how event listening is managed for each modal.

If we think further, we can imagine an event manager that will be called once (like `NgxSmartModalService` and that will listen for events and send them back to each modal marked as "listening for events".

Cheers! 🖖

**Comment by mduran-nerd** [comment]
@maximelafarie Do you have a planned date for the next release?

**Comment by mduran-nerd** [comment]
@maximelafarie I've submitted a PR that fixes this issue:
https://github.com/biig-io/ngx-smart-modal/pull/141

Could you have a look?

**Comment by mduran-nerd** [comment]
@maximelafarie I see that you've merged the PR. Do you have a timeline for when you'll be publishing a new version of the modal to npm?
