### ISSUE TITLE
Setting Higher Index

### ISSUE THREAD

**Issue by Kalpesh300** [biig-io/ngx-smart-modal#135]
**I'm submitting a ...** 
```
[ ] bug report
[ x ] feature request
[ ] support request
```

There is a method to get a higher z-index value. But there is not any method to set this higher z-index value to some modal. 
What I mean is, let's assume I opened a modal named **A**. This modal has a button to open another modal named **B**. I know if I put modal selectors properly in HTML **B** can be opened over **A**.
But if I have some other requirements, I should be able to assign a higher z-index value to modal, provided one has modal-ID.

My conclusion, there should be a method something like `setHigherIndex(modal-id)`.

Thanks.

**Comment by maximelafarie** [comment]
Hi @Kalpesh300. No, there is no method to add a higher `z-index` value. We only implemented a getter called `getHigherIndex()` which helps for modal managing.

What we want to avoid is to have several modals with same `z-index` values. That's why if you want to change the z-index of a modal, you shall do it with the modal `customClass` option or your own way.
