### ISSUE TITLE
Allow opening modal via class reference

### ISSUE THREAD

**Issue by Humberd** [biig-io/ngx-smart-modal#171]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
To open a modal you have to pass an id of **existing** instance of component or a brand new instance of a component.

**Expected behavior**
Allow to create a modal like this:

```typescript
dialogService.open(UserProfileComponent);
```

**What is the motivation / use case for changing the behavior?**

The current problem is that I define modals per component, but I want to define per application. For example: If I have a routing component A, which defined a modal. Now If I go to route B I can no longer open the modal, becuase its instance had already been gone before entering a new route.

**Comment by khylias** [comment]
Hi @Humberd,

In your case, I think you can set the modal markup into your main app template and access to it with `NgxSmartModalService`. 

Furthermore, with this feature, the unknown is the placement of the modal in the component's HTML. 
What do you think @maximelafarie @marco10024 ?

**Comment by Humberd** [comment]
In Angular Material they did the same https://github.com/angular/material2/blob/master/src/lib/dialog/dialog.ts#L127

**Comment by maximelafarie** [comment]
Hi @Humberd! Thank you for your issue,

Do you have any shared component between your routes? Then, with the `NgxSmartModalService` you can inject data in this "global" modal and change its content dynamically.

@khylias I don't think it would be a big deal, because the modal will be default-positioned as if you declare it without any other class or style. We need to think more about that.

**Comment by maximelafarie** [comment]
I experimented some things like `new NgxSmartModalComponent(...)` but given that you need to pass constructor's dependencies injection, it's not very user-friendly.

I think you can do it so anyway but you'll probably need to inject the instance and / or attach it to an element in your template because as @khylias said, the modal needs a reference in the DOM to get well positioned.

Since your issue hasn't a huge asking frequency, it won't be a priority for us until we or a large amount of users need it. 😉

Btw, let us know if you succeeded with suggested solution or your own! 🖖

**Comment by benshabatnoam** [comment]
> Since your issue hasn't a huge asking frequency, it won't be a priority for us until we or a large amount of users need it. 😉

I need this in my projects. Is it 'large amount of users' already?  😉

I think @thardy in this [issue](https://github.com/biig-io/ngx-smart-modal/issues/184#issue-415330534) described it well: 

> The current implementation promotes tight coupling between the consumer of the modal and the modal template itself.

**Comment by maximelafarie** [comment]
Hi @Humberd and @benshabatnoam!

As it's a well asked feature, we added it to our "May Milestone". This new feature will be available soon and will be released as a minor version.

@marco10024 is in charge of this feature.

**Comment by maximelafarie** [comment]
It will be finally released today as `7.2.0` 🎉🚀 
Cheers! 🖖

**Comment by benshabatnoam** [comment]
You guys are awesome, we've been waiting for this change since this issue was opened. Thanks a lot!!!

**Comment by maximelafarie** [comment]
Thank you for the kind words! We're also excited to release this feature! (without any breaking changes 😎)

![you-got-it](https://user-images.githubusercontent.com/5319267/65223580-c9299680-dac1-11e9-8b65-1f440f09c465.gif)

You can already check the way you will be able to create modals via class reference [here](https://github.com/biig-io/ngx-smart-modal#you-can-also-create-your-modal-from-your-typescript-file--since-720-)! 😉
