### ISSUE TITLE
When setData in AfterViewInit ExpressionChangedAfterItHasBeenCheckedError 

### ISSUE THREAD

**Issue by jjmato** [biig-io/ngx-smart-modal#201]
**I'm submitting a ...**  (check one with "x")
```
[*] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

Set data on after view init trow ExpressionChangedAfterItHasBeenCheckedError.
If set data on init, the data is dont show.

**Expected behavior**

Show data in modal whitout errors.

**Reproduction of the problem**
https://stackblitz.com/edit/ngxsmartmodal-expressionchangedafterithasbeencheckederror
https://github.com/jjmato/ngxsmartmodal-expressionchangedafterithasbeencheckederror

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Smart Modal version:** ^7.1.0

* **Angular version:** ^7.2.5

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by khylias** [comment]
Hi @jjmato,
thanks for your formatted issue.
I took a look on your stackblitz and this error happen because `ngIf` status change between [angular's lifecycle hooks](https://angular.io/guide/lifecycle-hooks) `ngAfterViewInit` and `ngAfterViewChecked`.

However, if you still want to add your data into your modal at the `ngAfterViewInit`, you must add `ChangeDetectorRef` into your component to force angular to recheck view: 
```
constructor(private _cdr: ChangeDetectorRef, ...)
[...]
ngAfterViewInit(){
    const data = {htmlText:this.htmlText};
    this._modalSrv.setModalData(data, this.MODAL_ID);
    this._cdr.detectChanges();
 }
```
