### ISSUE TITLE
Select2 inside ngx-smart-modal doesn't work

### ISSUE THREAD

**Issue by amin79** [biig-io/ngx-smart-modal#232]
Hello again,

here is the link of stackblitz. Sorry if is not flowing completely the rules . My  English is not good enough and i'm also new in Github and angular and stackblitz :)

https://stackblitz.com/edit/angular-l2yx5m?file=src%2Fapp%2Fapp.component.html

**Comment by maximelafarie** [comment]
Hi @amin79.

Since it's not a library-related issue but more a lack of comprehension of how Angular lifecycle hooks work, I answered you directly on your Stackoverflow thread: https://stackoverflow.com/a/58114776/2724204

I added the fixed example and I added some documentation references to help you understand why it didn't worked.

Feel free to upvote and accept the answer if it helped you to solve your issue.

Cheers! 🖖

**Comment by amin79** [comment]
Thank you very very much :)
