### ISSUE TITLE
Compatibility with IE11

### ISSUE THREAD

**Issue by rsmachir** [biig-io/ngx-smart-modal#240]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

In IE 11 - Modal window does not open at all,  console throws "Application error has occurred: TypeError: Object doesn't support this action" message.

**Expected behavior**

Modal window should open.

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Angular 8.2.9 and ngx-smart-modal version 7.2.1.

* **Smart Modal version:** 0.8.x

* **Angular version:** 2.0.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by khylias** [comment]
Hi @rsmachir,

thanks to report this issue. Have you tested by activating the polyfills of your project?

**Comment by rsmachir** [comment]
Ever since Angular 8’s differential loading and targeted browser list, I have minimal polyfills turned on.   That has worked well till your version 7.1.1.   For now I reverted back to this version, so I can stay up with Angular updates.

**Comment by khylias** [comment]
It seems that the problem is indeed coming from [Angular himself](https://github.com/angular/angular-cli/issues/14455). The problem is therefore not related to ngx-smart-modal.

**Comment by DanWebb** [comment]
I've tried disabling differential loading completely, I still see the error and can't get any modals to launch in IE11. The modals on the [demo page](https://biig-io.github.io/ngx-smart-modal/#/demo) also do not work in IE11.

I think this needs a bit more investigation.

**Comment by khylias** [comment]
The demonstration is done with Angular 8, which by default provides a [browserlist file](https://github.com/biig-io/ngx-smart-modal/blob/master/browserslist) that defines the list of supported browsers. IE11 is not one of them.

As announced above, the compatibility of your Angular 8 and NgxSmartModal project is therefore a matter of your Angular configuration itself.

**Comment by DanWebb** [comment]
The project which I'm reproducing the error on has the following browserlist configuration `> 0.5%, last 2 versions, Firefox ESR, not dead` this includes IE11.

Everything else on the project continues to work on IE11, including ngx-smart-modal 7.1.1 or earlier.

I'm afraid this points to an incompatibility in the lib with IE11.

I'd happily be proved wrong if you could provide the config or polyfills you used to get it working during your tests, I'm sure that would be helpful to others trying to use the library too.

If not, I think at least the fact there's an issue here should be acknowledged by re-opening this. Then, I'll try investigating further when I get time to see if the issue can be pinpointed further because it'd be a shame to be stuck on 7.1.1 and miss out on all the great updates you guys keep releasing!

**Comment by KrishnaSharmaCC** [comment]
@khylias , @DanWebb , i faced the same issue. and fixed it by adding this [polyfill](codewithjason.com/add-test-coverage-report-angular-cli-project/) in `polyfills.ts`. Hope this helps..
```
(function () {
    function CustomEvent ( event, params ) {
      params = params || { bubbles: false, cancelable: false, detail: undefined };
      const evt = document.createEvent( 'CustomEvent' );
      evt.initCustomEvent( event, params.bubbles, params.cancelable, params.detail );
      return evt;
     }
    CustomEvent.prototype = window['Event'].prototype;
    window['CustomEvent'] = <any>CustomEvent;
  })();
```
